INCLUDE <P18F4321.INC>

		ORG 	0x50			; STARTING LOCATION REQUESTED BY ASSIGNMENT
	
		MOVLW	0x11			; ARBITRARY VALUE TO VERIFY CODE FUNCTION
		MOVWF	0x40			; ALLOCATE ADDRESS TO STORE ARBITRARY VALUE

		MOVLW	0x02			; TEST THE CODE BY INSERTING A NUMBER
	
;	THE FOLLOWING CODE STATEMENTS WILL DEFINE THE CONDITION TESTING:

		ANDLW	0x01			; MASK THE LSB TO DETERMINE WHETHER ODD OR EVEN
	 	BZ		DOWN			; BRANCH DOWN IF RESULT IS 0x00 -> EVEN
		SETF	0x40			; SET 0x40 IF RESULT IS 0x01 (NOT ZERO) -> ODD
		SLEEP					; HALT PROGRAM 
DOWN	CLRF	0x40			; CLEAR 0x40 IF RESULT IS 0x00

SLEEP
END
	