INCLUDE <P18F4321.INC>

		ORG		0x100			; LOCATION SPECIFIED BY INSTRUCTIONS
PARITY	EQU		0x60			; EQUATE ADDRESS [0x60] W/ PARITY
RESULT 	EQU		0x50			; EQUATE ADDRESS [0x50] W/ RESULT
COUNTER EQU		0x51			; EQUATE ADDRESS [0x51] W/ COUNTER
TEMP	EQU		0x52			; EQUATE ADDRESS [0x52] W/ TEMP STORAGE

		MOVLW	0x07			; ENTER ARBITRARY VALUE TO WREG
		MOVWF	0x70			; STORE VALUE IN REGISTER [0x70]
		MOVLW	0x08			; ENTER COUNTER VALUE OF 8
		MOVWF	COUNTER			; STORE VALUE IN COUNTER [0x50]
		CLRF	WREG			; CLEAR THE WORKING REGISTER
		CLRF	TEMP			; INITIALIZE TEMP TO 0x00

; LOOP TO ROTATE BITS FROM [0x70] AND ADD WITH EACH ITERATION
BACK	RRCF	0x70			; ROTATE AND STORE IN TEMP
		ADDWFC	TEMP			; ADD VALUE TO WREG
		BCF		STATUS,C		; CLEAR THE CARRY FLAG TO 0
		DECF	COUNTER			; DECREMENET THE COUNTER
		BNZ		BACK			; BRANCH IF COUNTER != 0x00

; LOOP IS COMPLETE AND VALUE SHOULD REPRESENT THE PARITY
; DEFINE LOOP TO CHECK IF THE PARITY IS EVEN OR ODD
		MOVFF	TEMP,PARITY		; MOVE TEMP TO PARITY
		MOVLW	0x01			; MOVE 0x01 INTO WREG
		ANDWF	PARITY			; MASKING TO DETERMINE IF ODD OR EVEN (ISOLATE LSB)
		BTFSC	PARITY,0		; IF 0th BIT IS D'0', SKIP
		MOVLW	0xEA			; VALUE TO STORE IF ODD
		BTFSS	PARITY,0		; IF 0th BIT IS D'1', SKIP
		MOVLW	0xDA			; VALUE TO STORE IF EVEN
		MOVWF	RESULT			; MOVE INTO RESULT ADDRESS [0x50]
		
SLEEP
END